;;; JHR - maille inox 2D, deux contours fermes, millimetres.
;;; JHRMAILLE / JHRMAILLEPARAM. Aucun contour source modifie.
;;; Cables : largeur geometrique reelle ; composants et contenu sur calque 0.
;;; Les accessoires sont une representation, pas un gabarit de sertissage.
(vl-load-com)
(if (not *wm:cfg*)
  (setq *wm:cfg* '((mw . 60.0) (ml . 104.0) (wire . 1.5) (lace . 2.0)
    (gap . 20.0) (sleeve-l . 5.5) (sleeve-h . 5.7) (angle . 0.0)
    (stops . 12) (maxnodes . 15000))))
(defun wm:fail (msg) (setq wm:reason msg) (exit))
(defun wm:floor (x) (if (< x (fix x)) (1- (fix x)) (fix x)))
(defun wm:cfg (k) (cdr (assoc k *wm:cfg*)))
(defun wm:set (k v) (setq *wm:cfg* (subst (cons k v) (assoc k *wm:cfg*) *wm:cfg*)))
(defun wm:add (a b) (mapcar '+ a b))
(defun wm:sub (a b) (mapcar '- a b))
(defun wm:mul (a s) (mapcar '(lambda (v) (* v s)) a))
(defun wm:dot (a b) (+ (* (car a) (car b)) (* (cadr a) (cadr b))))
(defun wm:cross (a b) (- (* (car a) (cadr b)) (* (cadr a) (car b))))
(defun wm:len (a) (sqrt (wm:dot a a)))
(defun wm:unit (a / l) (setq l (wm:len a)) (if (> l 1e-9) (wm:mul a (/ 1.0 l)) '(1.0 0.0)))
(defun wm:lerp (a b t0) (wm:add a (wm:mul (wm:sub b a) t0)))
(defun wm:rot (p ang) (list (- (* (car p) (cos ang)) (* (cadr p) (sin ang))) (+ (* (car p) (sin ang)) (* (cadr p) (cos ang)))))
(defun wm:local (p) (wm:rot (wm:sub (list (car p) (cadr p)) wm:origin) (- wm:angle)))
(defun wm:poly (en / end i n j p bul d0 d1 out)
  (setq end (fix (vlax-curve-getEndParam en)) i 0 out nil)
  (repeat end
    (setq bul (vla-GetBulge (vlax-ename->vla-object en) i)
          d0 (vlax-curve-getDistAtParam en i) d1 (vlax-curve-getDistAtParam en (1+ i))
          n (if (< (abs bul) 1e-10) 1 (max 4 (fix (+ 1 (/ (- d1 d0) 3.0))))) j 0)
    (repeat n (setq p (vlax-curve-getPointAtParam en (+ i (/ (float j) n))) out (cons (wm:local p) out) j (1+ j)))
    (setq i (1+ i)))
  (reverse out))
(defun wm:edges (p) (mapcar 'list p (append (cdr p) (list (car p)))))
(defun wm:area (p / s e) (setq s 0.0) (foreach e (wm:edges p) (setq s (+ s (wm:cross (car e) (cadr e))))) (/ s 2.0))
(defun wm:near (p poly / best bd chain e a b v t0 q dist len)
  (setq bd 1e99 chain 0.0)
  (foreach e (wm:edges poly)
    (setq a (car e) b (cadr e) v (wm:sub b a) len (wm:len v))
    (if (> len 1e-9)
      (progn (setq t0 (max 0.0 (min 1.0 (/ (wm:dot (wm:sub p a) v) (* len len)))) q (wm:lerp a b t0) dist (distance p q))
        (if (< dist bd) (setq bd dist best (list q (wm:unit v) (+ chain (* len t0)))))
        (setq chain (+ chain len)))))
  best)
(defun wm:inside (p poly / odd e a b x y)
  (setq odd nil x (car p) y (cadr p))
  (if (< (distance p (car (wm:near p poly))) 1e-6) T
    (progn (foreach e (wm:edges poly)
      (setq a (car e) b (cadr e))
      (if (and (not (equal (> (cadr a) y) (> (cadr b) y)))
        (< x (+ (car a) (* (- y (cadr a)) (/ (- (car b) (car a)) (- (cadr b) (cadr a)))))))
        (setq odd (not odd)))) odd)))
(defun wm:hit (a b c d / r s det t0 u)
  (setq r (wm:sub b a) s (wm:sub d c) det (wm:cross r s))
  (if (> (abs det) 1e-10)
    (progn (setq t0 (/ (wm:cross (wm:sub c a) s) det) u (/ (wm:cross (wm:sub c a) r) det))
      (if (and (>= t0 -1e-8) (<= t0 1.00000001) (>= u -1e-8) (<= u 1.00000001)) (max 0.0 (min 1.0 t0))))))
(defun wm:breaks (a b polys / ts poly edge v)
  (setq ts '(0.0 1.0))
  (foreach poly polys (foreach edge (wm:edges poly) (if (setq v (wm:hit a b (car edge) (cadr edge))) (setq ts (cons v ts)))))
  (vl-sort ts '<))
(defun wm:clip (a b poly / ts s e mid out)
  (setq ts (wm:breaks a b (list poly)) out nil)
  (while (cdr ts)
    (setq s (car ts) e (cadr ts) mid (wm:lerp a b (/ (+ s e) 2.0)))
    (if (and (> (- e s) 1e-8) (wm:inside mid poly)) (setq out (cons (list (wm:lerp a b s) (wm:lerp a b e)) out)))
    (setq ts (cdr ts))) (reverse out))
(defun wm:pline-data (pts width closed / r)
  (setq r (list '(0 . "LWPOLYLINE") '(100 . "AcDbEntity") '(8 . "0") '(62 . 0) '(6 . "Continuous") '(370 . 0)
    '(100 . "AcDbPolyline") (cons 90 (length pts)) (cons 70 (if closed 1 0)) (cons 43 width)))
  (append r (mapcar '(lambda (p) (cons 10 p)) pts)))
(defun wm:draw (pts width closed) (setq wm:shapes (cons (wm:pline-data pts width closed) wm:shapes)))
(defun wm:insert-data (name p ang)
  (list '(0 . "INSERT") '(100 . "AcDbEntity") '(8 . "0") '(62 . 0) '(6 . "Continuous")
    '(100 . "AcDbBlockReference") (cons 2 name) (cons 10 (append p '(0.0))) '(41 . 1.0) '(42 . 1.0) '(43 . 1.0) (cons 50 ang)))
(defun wm:insert (name p ang) (setq wm:shapes (cons (wm:insert-data name p ang) wm:shapes)))
(defun wm:bezier (a b c d / i t0 u pts)
  (setq i 0 pts nil)
  (repeat 17 (setq t0 (/ i 16.0) u (- 1.0 t0) pts (cons
    (wm:add (wm:add (wm:mul a (* u u u)) (wm:mul b (* 3 u u t0)))
      (wm:add (wm:mul c (* 3 u t0 t0)) (wm:mul d (* t0 t0 t0)))) pts) i (1+ i))) (reverse pts))
(defun wm:key (p) (strcat (rtos (car p) 2 4) ":" (rtos (cadr p) 2 4)))
(defun wm:cut (p grid-a grid-b poly / key target info kind)
  (setq key (wm:key p))
  (if (not (assoc key wm:cuts))
    (progn (setq target
      (cond ((not (wm:inside grid-a poly)) grid-a) ((not (wm:inside grid-b poly)) grid-b) (T p))
      info (wm:near p wm:inner) kind (if (> (abs (car (cadr info))) 0.7071) "LOOP" "EYE"))
      (setq wm:cuts (cons (list key (strcat kind ":" (wm:key target)) kind p) wm:cuts)))))
(defun wm:circle-points (centre radius / j pts)
  (setq j 0 pts nil) (repeat 25
    (setq pts (cons (wm:add centre (list (* radius (cos (* 2 pi (/ j 24.0)))) (* radius (sin (* 2 pi (/ j 24.0)))))) pts) j (1+ j)))
  (reverse pts))
(defun wm:terminals (/ groups rec group pts p info tangent normal sign bow anchor a b count)
  (setq groups nil wm:anchors nil sign (if (> (wm:area wm:inner) 0) 1.0 -1.0) wm:eyes 0 wm:loops 0)
  (foreach rec wm:cuts
    (setq group (assoc (cadr rec) groups))
    (if group (setq groups (subst (list (car group) (cadr group) (cons (cadddr rec) (caddr group))) group groups))
      (setq groups (cons (list (cadr rec) (caddr rec) (list (cadddr rec))) groups))))
  (foreach group groups
    (setq pts (caddr group) count (length pts) p '(0.0 0.0))
    (foreach a pts (setq p (wm:add p a))) (setq p (wm:mul p (/ 1.0 count))
      info (wm:near p wm:inner) tangent (cadr info) normal (wm:mul (list (cadr tangent) (- (car tangent))) sign))
    (if (= (cadr group) "LOOP")
      (progn (setq anchor p wm:loops (1+ wm:loops)))
      (progn
        ;; Eye replaces the sleeve at the outward vertex of a whole diamond.
        (setq p (wm:sub p (wm:mul normal (/ (wm:cfg 'sleeve-l) 2.0))))
        (wm:insert "JHR_WEBNET_OEIL_0150_B16_H8_3_V1" p (angle '(0.0 0.0) normal))
        (setq anchor (wm:add p (wm:mul normal 12.0)) wm:eyes (1+ wm:eyes))))
    (setq wm:anchors (cons (list (caddr (wm:near anchor wm:inner)) anchor (cadr group)) wm:anchors))))
(defun wm:mesh (poly / xs ys xmin xmax ymin ymax sx sy nx ny row col row0 col0 centre verts ed a b key edges nodes found neighbors v p info kind half pair)
  (setq xs (mapcar 'car poly) ys (mapcar 'cadr poly) xmin (apply 'min xs) xmax (apply 'max xs) ymin (apply 'min ys) ymax (apply 'max ys)
    sx (/ (wm:cfg 'ml) 2.0) sy (/ (wm:cfg 'mw) 2.0)
    nx (+ 4 (fix (/ (- xmax xmin) sx))) ny (+ 4 (fix (/ (- ymax ymin) sy))) edges nil nodes nil)
  (if (> (* nx ny) (wm:cfg 'maxnodes)) (wm:fail "Surface trop grande : limite de securite 15000 noeuds. Diviser le panneau."))
  (setq row0 (1- (wm:floor (/ ymin sy))) col0 (1- (wm:floor (/ xmin sx))) row row0)
  (repeat ny
    (setq col col0)
    (repeat nx
      (if (/= (rem (+ row col) 2) 0)
        (progn (setq centre (list (* col sx) (* row sy))
          verts (mapcar '(lambda (v) (wm:add centre v)) (list (list (- sx) 0.0) (list 0.0 sy) (list sx 0.0) (list 0.0 (- sy)))))
          ;; A cell is admitted only if all four vertices and all its edges fit.
          (if (and (vl-every '(lambda (v) (wm:inside v poly)) verts)
            (vl-every '(lambda (ed) (and (= (length (wm:clip (car ed) (cadr ed) poly)) 1)
              (equal (car (car (wm:clip (car ed) (cadr ed) poly))) (car ed) 1e-5)
              (equal (cadr (car (wm:clip (car ed) (cadr ed) poly))) (cadr ed) 1e-5))) (wm:edges verts)))
            (foreach ed (wm:edges verts)
              (setq a (car ed) b (cadr ed))
              (if (> (car a) (car b)) (setq v a a b b v))
              (setq key (strcat (wm:key a) "/" (wm:key b)))
              (if (not (assoc key edges))
                (progn (setq edges (cons (list key a b) edges))
                  (foreach pair (list (list a b) (list b a))
                    (setq p (car pair) key (wm:key p) found (assoc key nodes))
                    (if found (setq nodes (subst (list key p (cons (cadr pair) (caddr found))) found nodes))
                      (setq nodes (cons (list key p (list (cadr pair))) nodes))))))))))
      (setq col (1+ col))) (setq row (1+ row)))
  (setq half (/ (wm:cfg 'sleeve-l) 2.0))
  (foreach ed edges
    (setq a (wm:add (cadr ed) (list half 0.0)) b (wm:sub (caddr ed) (list half 0.0)))
    (wm:draw (wm:bezier a (wm:add a '(8.0 0.0)) (wm:sub b '(8.0 0.0)) b) (wm:cfg 'wire) nil))
  (foreach found nodes
    (setq p (cadr found) neighbors (caddr found) kind nil)
    (if (= (length neighbors) 2)
      (progn (setq info (wm:near p wm:inner) kind (if (> (abs (car (cadr info))) 0.7071) "LOOP" "EYE"))
        (setq wm:cuts (cons (list (car found) (car found) kind p) wm:cuts))))
    (if (/= kind "EYE") (progn (wm:insert wm:bead p 0.0) (setq wm:nodes (1+ wm:nodes)))))
  (princ))
(defun wm:back (pts / edges e ts s t0 mid run seg)
  (foreach e (mapcar 'list pts (cdr pts))
    (setq ts (wm:breaks (car e) (cadr e) (list wm:inner wm:outer)))
    (while (cdr ts)
      (setq s (car ts) t0 (cadr ts) mid (wm:lerp (car e) (cadr e) (/ (+ s t0) 2.0)))
      (if (or (wm:inside mid wm:inner) (not (wm:inside mid wm:outer)))
        (progn (setq seg (list (wm:lerp (car e) (cadr e) s) (wm:lerp (car e) (cadr e) t0)))
          (if (and run (< (distance (car run) (car seg)) 1e-5)) (setq run (cons (cadr seg) run))
            (progn (if run (wm:draw (reverse run) (wm:cfg 'lace) nil)) (setq run (list (cadr seg) (car seg))))))
        (progn (if run (wm:draw (reverse run) (wm:cfg 'lace) nil)) (setq run nil)))
      (setq ts (cdr ts))))
  (if run (wm:draw (reverse run) (wm:cfg 'lace) nil)))
(defun wm:at (chain poly / per e len a b out)
  (setq per 0.0) (foreach e (wm:edges poly) (setq per (+ per (distance (car e) (cadr e)))))
  (setq chain (rem (+ chain per) per))
  (foreach e (wm:edges poly)
    (if (not out) (progn (setq a (car e) b (cadr e) len (distance a b))
      (if (<= chain len) (setq out (list (wm:lerp a b (/ chain len)) (wm:unit (wm:sub b a))))
        (setq chain (- chain len)))))) out)
(defun wm:lace (poly / anchors pair p nextp info normal tangent outerp ray ts v sign index pitch per phase edge1 edge2 radius rise arc peak side width turn-info normal-p normal-next h hp hn front-path back-path k e)
  (setq anchors (vl-sort wm:anchors '(lambda (a b) (< (car a) (car b))))
    index 0 wm:boundary (length anchors) sign (if (> (wm:area wm:inner) 0) 1.0 -1.0) per 0.0 k 0.55228475)
  (foreach e (wm:edges wm:inner) (setq per (+ per (distance (car e) (cadr e)))))
  (foreach pair (mapcar 'list anchors (append (cdr anchors) (list (car anchors))))
    (setq p (cadar pair) nextp (cadadr pair) pitch (- (caadr pair) (caar pair)))
    (if (<= pitch 0) (setq pitch (+ pitch per)))
    (setq phase (+ (caar pair) (* 0.46 pitch)) info (wm:at phase wm:inner) tangent (cadr info)
      normal (wm:mul (list (cadr tangent) (- (car tangent))) sign)
      ray (wm:add (car info) (wm:mul normal 10000.0)) ts nil)
    (foreach e (wm:edges wm:outer) (if (setq v (wm:hit (car info) ray (car e) (cadr e))) (if (> v 1e-7) (setq ts (cons v ts)))))
    (if (not ts) (wm:fail "Le contour exterieur ne permet pas de retrouver le cadre a cette rive."))
    (setq outerp (wm:lerp (car info) ray (apply 'min ts)) width (distance (car info) outerp)
      turn-info (wm:near outerp wm:outer) tangent (cadr turn-info)
      normal (wm:mul (list (cadr tangent) (- (car tangent))) sign)
      side (> (abs (car normal)) (abs (cadr normal))))
    ;; Actual local frame width drives both the return and the rounding.
    ;; The spacing between successive mesh vertices also limits the loop size.
    (setq radius (min (* width (if side 0.14 0.28)) (* pitch 0.18))
      rise (* radius (if side 0.85 0.50))
      edge1 (wm:sub outerp (wm:mul tangent radius)) edge2 (wm:add outerp (wm:mul tangent radius))
      peak (wm:add outerp (wm:mul normal rise))
      info (wm:near p wm:inner) normal-p (wm:mul (list (cadr (cadr info)) (- (car (cadr info)))) sign)
      info (wm:near nextp wm:inner) normal-next (wm:mul (list (cadr (cadr info)) (- (car (cadr info)))) sign)
      h (min (* width 0.35) (* pitch 0.22))
      hp (min (* width 0.16) (* (distance p outerp) 0.12))
      hn (min (* width 0.16) (* (distance nextp outerp) 0.12)))
    ;; Two joined quarter-ellipses; tangents agree with both cable legs.
    (setq arc (wm:bezier edge1 (wm:add edge1 (wm:mul normal (* k rise)))
      (wm:sub peak (wm:mul tangent (* k radius))) peak))
    (setq arc (append arc (cdr (wm:bezier peak (wm:add peak (wm:mul tangent (* k radius)))
      (wm:add edge2 (wm:mul normal (* k rise))) edge2))))
    (if side
      (setq back-path (wm:bezier p (wm:add p (wm:mul normal-p hp)) (wm:sub edge1 (wm:mul normal h)) edge1)
        front-path (wm:bezier edge2 (wm:sub edge2 (wm:mul normal h)) (wm:add nextp (wm:mul normal-next hn)) nextp))
      (setq back-path (wm:bezier nextp (wm:add nextp (wm:mul normal-next hn)) (wm:sub edge2 (wm:mul normal h)) edge2)
        front-path (wm:bezier edge1 (wm:sub edge1 (wm:mul normal h)) (wm:add p (wm:mul normal-p hp)) p)))
    (wm:back back-path)
    ;; One continuous polyline removes seams between the round and the visible leg.
    (wm:draw (append (if side arc (reverse arc)) (cdr front-path)) (wm:cfg 'lace) nil)
    (if (and (= (caddar pair) "EYE") (= (rem index (wm:cfg 'stops)) 0))
      (wm:insert "JHR_WEBNET_BUTEE_4x4_V1" (wm:lerp p edge1 0.16) (angle p edge1)))
    (setq index (1+ index))))
(defun wm:block (name shapes / data)
  (if (tblsearch "BLOCK" name) (wm:fail "Nom de bloc deja utilise."))
  (setq wm:changed T)
  (entmake (list '(0 . "BLOCK") '(8 . "0") (cons 2 name) '(70 . 0) '(10 0.0 0.0 0.0)))
  (foreach data shapes (if (not (entmake data)) (wm:fail "Creation d un composant impossible.")))
  (entmake '((0 . "ENDBLK") (8 . "0"))))
(defun wm:bead-block (name w h / shapes x y r verts)
  (if (not (tblsearch "BLOCK" name))
    (progn (setq x (/ w 2.0) y (/ h 2.0) r 0.45
      verts (list (list (- x) (- r y)) (list (- r x) (- y)) (list (- x r) (- y)) (list x (- r y))
        (list x (- y r)) (list (- x r) y) (list (- r x) y) (list (- x) (- y r))))
      (setq shapes (list (wm:pline-data verts 0.12 T)
        (wm:pline-data (list (list (+ (- x) 0.7) (+ (- y) 0.5)) (list (+ (- x) 0.7) (- y 0.5))) 0.10 nil)
        (wm:pline-data (list (list (- x 0.7) (+ (- y) 0.5)) (list (- x 0.7) (- y 0.5))) 0.10 nil)))
      (wm:block name shapes))))
(defun wm:eye-block (/ name outline holes pts j ang)
  (setq name "JHR_WEBNET_OEIL_0150_B16_H8_3_V1")
  (if (not (tblsearch "BLOCK" name))
    (progn (setq pts '((0.0 -2.0) (8.0 -4.15)) j 0)
      (repeat 17 (setq ang (+ (- (/ pi 2.0)) (* pi (/ j 16.0)))
        pts (append pts (list (list (+ 11.85 (* 4.15 (cos ang))) (* 4.15 (sin ang))))) j (1+ j)))
      (setq pts (append pts '((8.0 4.15) (0.0 2.0))))
      (wm:block name (list (wm:pline-data pts 0.15 T) (wm:pline-data (wm:circle-points '(12.0 0.0) 1.5) 0.12 T)
        (wm:pline-data '((1.5 -1.6) (1.5 1.6)) 0.10 nil) (wm:pline-data '((3.0 -1.6) (3.0 1.6)) 0.10 nil))))))
(defun wm:offset (en gap / obj results valid sign raw o p candidates)
  (setq obj (vlax-ename->vla-object en) valid nil)
  (foreach sign '(-1 1)
    (if (not valid)
      (progn (setq raw (vl-catch-all-apply 'vlax-invoke (list obj 'Offset (* sign gap))))
        (if (not (vl-catch-all-error-p raw))
          (progn (if raw (setq wm:changed T)) (setq candidates nil) (foreach o raw
            (setq wm:temps (cons o wm:temps) p (wm:poly (vlax-vla-object->ename o)))
            (if (and (> (abs (wm:area p)) 1.0) (< (abs (wm:area p)) (abs (wm:area wm:inner)))
                 (vl-every '(lambda (q) (wm:inside q wm:inner)) p)) (setq candidates (cons p candidates))))
          (if (> (length candidates) 1) (wm:fail "Le retrait divise le filet en plusieurs panneaux. Traiter chaque panneau separement."))
          (if candidates (setq valid (car candidates))))))))
  (if (not valid) (wm:fail "Retrait du filet impossible. Reduire le retrait ou verifier la polyligne interieure.")) valid)
(defun wm:validate (en / data)
  (setq data (entget en))
  (if (or (/= (cdr (assoc 0 data)) "LWPOLYLINE") (= (logand 1 (cdr (assoc 70 data))) 0))
    (wm:fail "Selectionner une polyligne 2D fermee."))
  (if (and (assoc 210 data) (not (equal (cdr (assoc 210 data)) '(0.0 0.0 1.0) 1e-8)))
    (wm:fail "Les contours doivent etre dessines dans le plan XY (normale Z).")) en)
(defun wm:selfcross (p / ed i j bad a b)
  (setq ed (wm:edges p) i 0 bad nil)
  (foreach a ed (setq j 0)
    (foreach b ed
      (if (and (> j (+ i 1)) (not (and (= i 0) (= j (1- (length ed))))) (wm:hit (car a) (cadr a) (car b) (cadr b))) (setq bad T))
      (setq j (1+ j))) (setq i (1+ i))) bad)
(defun wm:generate (inside outside / obj lo hi poly name index data ins first last shapes result)
  (setq wm:reason nil)
  (wm:validate inside) (wm:validate outside)
  (if (equal inside outside) (wm:fail "Les deux contours doivent etre differents."))
  (if (> (abs (- (cond ((cdr (assoc 38 (entget inside)))) (T 0.0)) (cond ((cdr (assoc 38 (entget outside)))) (T 0.0)))) 0.01)
    (wm:fail "Les deux contours doivent etre coplanaires."))
  (setq obj (vlax-ename->vla-object inside)) (vla-GetBoundingBox obj 'lo 'hi)
  (setq lo (vlax-safearray->list lo) hi (vlax-safearray->list hi)
    wm:origin (mapcar '(lambda (a b) (/ (+ a b) 2.0)) (list (car lo) (cadr lo)) (list (car hi) (cadr hi)))
    wm:angle (wm:cfg 'angle) wm:inner (wm:poly inside) wm:outer (wm:poly outside))
  (if (< (wm:area wm:inner) 0) (setq wm:inner (reverse wm:inner)))
  (if (< (wm:area wm:outer) 0) (setq wm:outer (reverse wm:outer)))
  (if (or (wm:selfcross wm:inner) (wm:selfcross wm:outer)) (wm:fail "Contour croise ou auto-intersectant."))
  (if (or (not (vl-every '(lambda (p) (wm:inside p wm:outer)) wm:inner))
          (vl-some '(lambda (a) (vl-some '(lambda (b) (wm:hit (car a) (cadr a) (car b) (cadr b))) (wm:edges wm:outer))) (wm:edges wm:inner)))
    (wm:fail "Le contour exterieur doit entourer strictement le contour interieur sans le couper."))
  (setq poly (wm:offset inside (wm:cfg 'gap)) wm:netpoly poly wm:anchors nil wm:cuts nil wm:shapes nil wm:nodes 0 wm:boundary 0
    wm:bead (strcat "JHR_WEBNET_DOUILLE_" (vl-string-translate "." "_" (rtos (wm:cfg 'sleeve-l) 2 2)) "x"
        (vl-string-translate "." "_" (rtos (wm:cfg 'sleeve-h) 2 2)) "_V1"))
  (princ "\nCreation de la maille et des douilles...") (wm:mesh poly)
  (wm:terminals)
  (if (< (length wm:anchors) 4) (wm:fail "Cadre trop petit pour ces dimensions de maille."))
  (wm:lace poly)
  (wm:eye-block)
  (wm:bead-block wm:bead (wm:cfg 'sleeve-l) (wm:cfg 'sleeve-h))
  (wm:bead-block "JHR_WEBNET_BUTEE_4x4_V1" 4.0 4.0)
  (setq index 1) (while (tblsearch "BLOCK" (strcat "JHR_MAILLE_2D_" (itoa index))) (setq index (1+ index)))
  (setq name (strcat "JHR_MAILLE_2D_" (itoa index))) (wm:block name (reverse wm:shapes))
  (setq data (wm:insert-data name wm:origin wm:angle))
  (setq data (subst (cons 8 (getvar "CLAYER")) (assoc 8 data) data)
    data (subst (cons 10 (list (car wm:origin) (cadr wm:origin) (caddr lo))) (assoc 10 data) data))
  (entmake data) (setq ins (entlast))
  (regapp "JHR_WEBNET")
  (entmod (append (entget ins) (list (list -3 (list "JHR_WEBNET" (cons 1000 "representation2D;maille_centre_centre;accessoires_schematiques")
    (cons 1040 (wm:cfg 'wire)) (cons 1040 (wm:cfg 'lace)) (cons 1040 (wm:cfg 'mw)) (cons 1040 (wm:cfg 'ml))
    (cons 1005 (cdr (assoc 5 (entget inside)))) (cons 1005 (cdr (assoc 5 (entget outside)))))))))
  (setq *wm:last* ins)
  (princ (strcat "\n" name " : " (itoa wm:nodes) " douilles de maille, " (itoa wm:boundary) " raccords de rive. Tout le contenu est sur le calque 0.")) ins)
(defun wm:cleanup () (foreach o wm:temps (vl-catch-all-apply 'vla-Delete (list o))) (setq wm:temps nil))
(defun c:JHRMAILLE (/ *error* doc inside outside result wm:temps wm:origin wm:angle wm:inner wm:outer wm:netpoly wm:shapes wm:anchors wm:nodes wm:boundary wm:bead wm:cuts wm:eyes wm:loops begun wm:reason wm:changed)
  (defun *error* (msg)
    (wm:cleanup) (if begun (vla-EndUndoMark doc))
    (if wm:reason (princ (strcat "\nMaille non creee : " wm:reason)))
    (if (and (not wm:reason) msg (not (wcmatch (strcase msg) "*CANCEL*,*QUIT*,*BREAK*,*ANNUL*"))) (princ (strcat "\nMaille non creee : " msg))) (princ))
  (if (not (member (getvar "INSUNITS") '(0 4))) (wm:fail "Dessiner en millimetres avant de lancer JHRMAILLE."))
  (if (not (= (getvar "TILEMODE") 1)) (wm:fail "Lancer la commande dans l espace objet."))
  (setq inside (car (entsel "\n1 - Contour FERME interieur du cadre : ")))
  (if inside (progn (wm:validate inside) (setq outside (car (entsel "\n2 - Contour FERME exterieur du cadre : ")))
    (if outside (progn
      (setq doc (vla-get-ActiveDocument (vlax-get-acad-object))) (vla-StartUndoMark doc) (setq begun T)
      (setq result (vl-catch-all-apply 'wm:generate (list inside outside))) (wm:cleanup)
      (vla-EndUndoMark doc) (setq begun nil)
      (if (vl-catch-all-error-p result) (progn (if wm:changed (command "_.UNDO" "1")) (princ (strcat "\nMaille non creee : " (if wm:reason wm:reason (vl-catch-all-error-message result)))))
        (progn (vla-Regen doc 1) (princ "\nUn seul bloc ajoute ; les deux contours sources sont conserves. ANNULER revient en une etape."))))))) (princ))
(defun wm:ask (k label / val)
  (initget 6) (setq val (getreal (strcat "\n" label " <" (rtos (wm:cfg k) 2 2) "> : ")))
  (if val (wm:set k val)))
(defun c:JHRMAILLEPARAM (/ a n)
  (foreach item '((mw "Petite diagonale centre / centre (mm)") (ml "Grande diagonale centre / centre (mm)")
      (wire "Diametre cable de maille (mm)") (lace "Diametre cable de lacage (mm)") (gap "Retrait filet / face interieure du cadre (mm)")
      (sleeve-l "Longueur dessinee de la douille (mm)") (sleeve-h "Largeur dessinee de la douille (mm)"))
    (wm:ask (car item) (cadr item)))
  (setq a (getangle (strcat "\nDirection de la grande diagonale <" (rtos (* 180.0 (/ (wm:cfg 'angle) pi)) 2 1) " deg> : ")))
  (if a (wm:set 'angle (+ a (angle '(0 0 0) (trans '(1 0 0) 1 0 T)))))
  (initget 6) (setq n (getint (strcat "\nPas des petites butees de rive <" (itoa (wm:cfg 'stops)) "> : ")))
  (if n (wm:set 'stops n)) (princ "\nParametres memorises pour cette session. Lancer JHRMAILLE.") (princ))
(princ "\nJHRMAILLE : interieur puis exterieur. JHRMAILLEPARAM : diametres, maille, retrait et orientation.")
(princ)
