;;; JHR - maille inox 2D, deux contours fermes, millimetres.
;;; JHRMAILLE / JHRMAILLEPARAM. Aucun contour source modifie.
;;; Cables : largeur geometrique reelle ; composants et contenu sur calque 0.
;;; Les accessoires sont une representation, pas un gabarit de sertissage.
(vl-load-com)
(if (not *wm:cfg*)
  (setq *wm:cfg* '((mw . 60.0) (ml . 104.0) (wire . 1.5) (lace . 2.0)
    (gap . 20.0) (sleeve-l . 5.5) (sleeve-h . 5.7) (angle . 0.0)
    (stops . 12) (maxnodes . 15000))))
;; Preserve session settings when reloading an older configuration.
(if (not (assoc 'corner-auto *wm:cfg*))
  (setq *wm:cfg* (append *wm:cfg* '((corner-auto . 1)))))
;; Old session configurations keep their values; default remains sleeved.
(if (not (assoc 'woven *wm:cfg*)) (setq *wm:cfg* (append *wm:cfg* '((woven . 0)))))
;; Portable folder lookup; manual NETLOAD also works without a support path.
(setq *wm:ui-root* (cond
  ((findfile "JhrMailleUi_v1_2.dll") (vl-filename-directory (findfile "JhrMailleUi_v1_2.dll")))
  ((findfile "JHR_Maille_2D.lsp") (vl-filename-directory (findfile "JHR_Maille_2D.lsp")))
  (*wm:ui-root* *wm:ui-root*) (T nil)))
(defun wm:tail (n items) (repeat n (setq items (cdr items))) items)
(defun wm:product-stamp ()
 (mapcar 'wm:cfg '(ml mw wire woven sleeve-l sleeve-h)))
(defun wm:product-current ()
 (if (and *wm:product* (equal *wm:product-stamp* (wm:product-stamp) 1e-8)) *wm:product*))
(defun wm:product-xdata ()
 (if (wm:product-current)
  (mapcar '(lambda (v) (cons 1000 v))
   (mapcar 'strcat '("reference_jakob=" "gamme=" "matiere_catalogue=") (wm:product-current)))))
(defun wm:half () (if (= (wm:cfg 'woven) 1) (* 2.5 (wm:cfg 'wire)) (/ (wm:cfg 'sleeve-l) 2.0)))
(defun wm:settings-valid (/ join)
 (setq join (* 2.0 (wm:half)))
 (if (or (<= (wm:cfg 'wire) 0) (<= (wm:cfg 'lace) 0) (<= (wm:cfg 'gap) 0)
   (<= (wm:cfg 'ml) (+ join (* 2 (wm:cfg 'wire))))
   (<= (wm:cfg 'mw) (* 4 (wm:cfg 'wire))))
   (wm:fail "Dimensions de maille trop petites pour le cable et la jonction. Verifier les parametres.")))
(defun wm:fail (msg) (setq wm:reason msg) (exit))
(defun wm:floor (x) (if (< x (fix x)) (1- (fix x)) (fix x)))
(defun wm:cfg (k) (cdr (assoc k *wm:cfg*)))
(defun wm:set (k v) (setq *wm:cfg* (subst (cons k v) (assoc k *wm:cfg*) *wm:cfg*)))
(defun wm:add (a b) (mapcar '+ a b))
(defun wm:sub (a b) (mapcar '- a b))
(defun wm:mul (a s) (mapcar '(lambda (v) (* v s)) a))
(defun wm:dot (a b) (+ (* (car a) (car b)) (* (cadr a) (cadr b))))
(defun wm:cross (a b) (- (* (car a) (cadr b)) (* (cadr a) (car b))))
(defun wm:len (a) (sqrt (wm:dot a a)))
(defun wm:unit (a / l) (setq l (wm:len a)) (if (> l 1e-9) (wm:mul a (/ 1.0 l)) '(1.0 0.0)))
(defun wm:lerp (a b t0) (wm:add a (wm:mul (wm:sub b a) t0)))
(defun wm:rot (p ang) (list (- (* (car p) (cos ang)) (* (cadr p) (sin ang))) (+ (* (car p) (sin ang)) (* (cadr p) (cos ang)))))
(defun wm:local (p) (wm:rot (wm:sub (list (car p) (cadr p)) wm:origin) (- wm:angle)))
(defun wm:poly (en / end i n j p bul d0 d1 out)
  (setq end (fix (vlax-curve-getEndParam en)) i 0 out nil)
  (repeat end
    (setq bul (vla-GetBulge (vlax-ename->vla-object en) i)
          d0 (vlax-curve-getDistAtParam en i) d1 (vlax-curve-getDistAtParam en (1+ i))
          n (if (< (abs bul) 1e-10) 1 (max 4 (fix (+ 1 (/ (- d1 d0) 3.0))))) j 0)
    (repeat n (setq p (vlax-curve-getPointAtParam en (+ i (/ (float j) n))) out (cons (wm:local p) out) j (1+ j)))
    (setq i (1+ i)))
  (reverse out))
(defun wm:edges (p) (mapcar 'list p (append (cdr p) (list (car p)))))
(defun wm:area (p / s e) (setq s 0.0) (foreach e (wm:edges p) (setq s (+ s (wm:cross (car e) (cadr e))))) (/ s 2.0))
(defun wm:near (p poly / best bd chain e a b v t0 q dist len)
  (setq bd 1e99 chain 0.0)
  (foreach e (wm:edges poly)
    (setq a (car e) b (cadr e) v (wm:sub b a) len (wm:len v))
    (if (> len 1e-9)
      (progn (setq t0 (max 0.0 (min 1.0 (/ (wm:dot (wm:sub p a) v) (* len len)))) q (wm:lerp a b t0) dist (distance p q))
        (if (< dist bd) (setq bd dist best (list q (wm:unit v) (+ chain (* len t0)))))
        (setq chain (+ chain len)))))
  best)
(defun wm:inside (p poly / odd e a b x y)
  (setq odd nil x (car p) y (cadr p))
  (if (< (distance p (car (wm:near p poly))) 1e-6) T
    (progn (foreach e (wm:edges poly)
      (setq a (car e) b (cadr e))
      (if (and (not (equal (> (cadr a) y) (> (cadr b) y)))
        (< x (+ (car a) (* (- y (cadr a)) (/ (- (car b) (car a)) (- (cadr b) (cadr a)))))))
        (setq odd (not odd)))) odd)))
(defun wm:hit (a b c d / r s det t0 u)
  (setq r (wm:sub b a) s (wm:sub d c) det (wm:cross r s))
  (if (> (abs det) 1e-10)
    (progn (setq t0 (/ (wm:cross (wm:sub c a) s) det) u (/ (wm:cross (wm:sub c a) r) det))
      (if (and (>= t0 -1e-8) (<= t0 1.00000001) (>= u -1e-8) (<= u 1.00000001)) (max 0.0 (min 1.0 t0))))))
(defun wm:breaks (a b polys / ts poly edge v)
  (setq ts '(0.0 1.0))
  (foreach poly polys (foreach edge (wm:edges poly) (if (setq v (wm:hit a b (car edge) (cadr edge))) (setq ts (cons v ts)))))
  (vl-sort ts '<))
(defun wm:clip (a b poly / ts s e mid out)
  (setq ts (wm:breaks a b (list poly)) out nil)
  (while (cdr ts)
    (setq s (car ts) e (cadr ts) mid (wm:lerp a b (/ (+ s e) 2.0)))
    (if (and (> (- e s) 1e-8) (wm:inside mid poly)) (setq out (cons (list (wm:lerp a b s) (wm:lerp a b e)) out)))
    (setq ts (cdr ts))) (reverse out))
(defun wm:pline-data (pts width closed / r)
  (setq r (list '(0 . "LWPOLYLINE") '(100 . "AcDbEntity") '(8 . "0") '(62 . 256) '(6 . "Continuous") '(370 . -1)
    '(100 . "AcDbPolyline") (cons 90 (length pts)) (cons 70 (if closed 1 0)) (cons 43 width)))
  (append r (mapcar '(lambda (p) (cons 10 p)) pts)))
(defun wm:draw (pts width closed) (setq wm:shapes (cons (wm:pline-data pts width closed) wm:shapes)))
(defun wm:insert-data (name p ang)
  (list '(0 . "INSERT") '(100 . "AcDbEntity") '(8 . "0") '(62 . 256) '(6 . "Continuous")
    '(100 . "AcDbBlockReference") (cons 2 name) (cons 10 (append p '(0.0))) '(41 . 1.0) '(42 . 1.0) '(43 . 1.0) (cons 50 ang)))
(defun wm:insert (name p ang) (setq wm:shapes (cons (wm:insert-data name p ang) wm:shapes)))
(defun wm:bezier (a b c d / i t0 u pts)
  (setq i 0 pts nil)
  (repeat 17 (setq t0 (/ i 16.0) u (- 1.0 t0) pts (cons
    (wm:add (wm:add (wm:mul a (* u u u)) (wm:mul b (* 3 u u t0)))
      (wm:add (wm:mul c (* 3 u t0 t0)) (wm:mul d (* t0 t0 t0)))) pts) i (1+ i))) (reverse pts))
(defun wm:key (p) (strcat (rtos (car p) 2 4) ":" (rtos (cadr p) 2 4)))
(defun wm:cut (p grid-a grid-b poly / key target info kind)
  (setq key (wm:key p))
  (if (not (assoc key wm:cuts))
    (progn (setq target
      (cond ((not (wm:inside grid-a poly)) grid-a) ((not (wm:inside grid-b poly)) grid-b) (T p))
      info (wm:near p wm:inner) kind (if (> (abs (car (cadr info))) 0.7071) "LOOP" "EYE"))
      (setq wm:cuts (cons (list key (strcat kind ":" (wm:key target)) kind p) wm:cuts)))))
(defun wm:circle-points (centre radius / j pts)
  (setq j 0 pts nil) (repeat 25
    (setq pts (cons (wm:add centre (list (* radius (cos (* 2 pi (/ j 24.0)))) (* radius (sin (* 2 pi (/ j 24.0)))))) pts) j (1+ j)))
  (reverse pts))
(defun wm:ray-near (p normal poly / ray ts e v)
  (setq ray (wm:add p (wm:mul normal 10000.0)) ts nil)
  (foreach e (wm:edges poly)
    (if (setq v (wm:hit p ray (car e) (cadr e)))
      (if (> v 1e-7) (setq ts (cons v ts)))))
  (if ts (wm:near (wm:lerp p ray (apply 'min ts)) poly) (wm:near p poly)))
(defun wm:terminals (/ groups rec group pts p info tangent normal sign bow anchor a b count)
  (setq groups nil wm:anchors nil sign (if (> (wm:area wm:inner) 0) 1.0 -1.0) wm:eyes 0 wm:loops 0)
  (foreach rec wm:cuts
    (setq group (assoc (cadr rec) groups))
    (if group (setq groups (subst (list (car group) (cadr group) (cons (cadddr rec) (caddr group)) (nth 3 group)) group groups))
      (setq groups (cons (list (cadr rec) (caddr rec) (list (cadddr rec)) (nth 4 rec)) groups))))
  (foreach group groups
    (setq pts (caddr group) count (length pts) p '(0.0 0.0))
    (foreach a pts (setq p (wm:add p a))) (setq p (wm:mul p (/ 1.0 count))
      info (wm:near p wm:inner) tangent (cadr info)
      normal (if (nth 3 group) (nth 3 group) (wm:mul (list (cadr tangent) (- (car tangent))) sign)))
    (if (= (cadr group) "LOOP")
      (progn (setq anchor p wm:loops (1+ wm:loops)))
      (progn
        ;; Eye replaces the sleeve at the outward vertex of a whole diamond.
        (setq p (wm:sub p (wm:mul normal (wm:half))))
        (wm:insert "JHR_WEBNET_OEIL_0150_B16_H8_3_V1" p (angle '(0.0 0.0) normal))
        (setq anchor (wm:add p (wm:mul normal 12.0)) wm:eyes (1+ wm:eyes))))
    (setq info (if (nth 3 group) (wm:ray-near anchor normal wm:inner) (wm:near anchor wm:inner)))
    (setq wm:anchors (cons (list (caddr info) anchor (cadr group) (nth 3 group)) wm:anchors))))
;; A rejected whole cell can leave a three-leg node near a frame corner.
;; Complete only its missing diagonal, when that grid endpoint AND the entire
;; cable fit within the inset polygon. End it with a lateral eye, not a bead.
(defun wm:tip-normal (tip direction / edges previous e t1 t2 n1 n2 normal best bd dist)
  (setq edges (wm:edges wm:inner) previous (car (reverse edges)) bd 1e99)
  (foreach e edges
    (setq t1 (wm:unit (wm:sub (cadr previous) (car previous)))
      t2 (wm:unit (wm:sub (cadr e) (car e))) dist (distance tip (car e)))
    (if (and (> (wm:cross t1 t2) 1e-6) (< (wm:dot t1 t2) 0.8660254)
             (< dist bd) (<= dist (wm:len (list (wm:cfg 'ml) (wm:cfg 'mw)))))
      (progn
        (setq n1 (list (cadr t1) (- (car t1))) n2 (list (cadr t2) (- (car t2)))
          normal (if (> (abs (car n1)) (abs (car n2))) n1 n2))
        (if (> (wm:dot direction normal) 1e-6) (setq best normal bd dist))))
    (setq previous e)) best)
(defun wm:missing-edges (nodes poly sx sy / extra tips found p neighbors tip key normal parts a b swap)
  (setq extra nil tips nil wm:extensions 0)
  (if (= (wm:cfg 'corner-auto) 1)
    (foreach found nodes
      (if (= (length (caddr found)) 3)
        (progn
          (setq p (cadr found) neighbors (caddr found))
          (foreach tip (mapcar '(lambda (v) (wm:add p v))
            (list (list sx sy) (list sx (- sy)) (list (- sx) sy) (list (- sx) (- sy))))
            (setq key (wm:key tip))
            (if (and (not (assoc key nodes)) (not (member key tips))
                (wm:inside tip poly) (setq normal (wm:tip-normal tip (wm:sub tip p)))
                (= (length (setq parts (wm:clip p tip poly))) 1)
                (equal (caar parts) p 1e-5) (equal (cadar parts) tip 1e-5))
              (progn
                (setq a p b tip)
                (if (> (car a) (car b)) (setq swap a a b b swap))
                (setq extra (cons (list (strcat (wm:key a) "/" (wm:key b)) a b) extra)
                  tips (cons key tips) wm:extensions (1+ wm:extensions)
                  wm:cuts (cons (list key key "EYE" tip normal) wm:cuts))))))))) extra)
;; Centre the largest lattice that fits an axis-aligned rectangular inset.
;; Fixed zero phase previously dropped an otherwise admissible cell column.
;; Keep the requested diagonals and minimum retreat; no stretching or clipping.
;; Non-rectangular polygons retain their exact whole-edge containment checks.
(defun wm:rect-layout (poly sx sy / xs ys xmin xmax ymin ymax cols rows)
  (setq xs (mapcar 'car poly) ys (mapcar 'cadr poly)
    xmin (apply 'min xs) xmax (apply 'max xs) ymin (apply 'min ys) ymax (apply 'max ys))
  (if (and (= (length poly) 4)
    (vl-every '(lambda (p) (and
      (or (equal (car p) xmin 1e-6) (equal (car p) xmax 1e-6))
      (or (equal (cadr p) ymin 1e-6) (equal (cadr p) ymax 1e-6)))) poly)
    (vl-every '(lambda (e) (or (equal (caar e) (caadr e) 1e-6)
      (equal (cadar e) (cadadr e) 1e-6))) (wm:edges poly)))
    (progn
      (setq cols (1+ (wm:floor (+ (/ (- xmax xmin (* 2.0 sx)) sx) 1e-8)))
        rows (1+ (wm:floor (+ (/ (- ymax ymin (* 2.0 sy)) sy) 1e-8))))
      (if (and (> cols 0) (> rows 0))
        (list cols rows
          (list (/ (- (+ xmin xmax) (* (1- cols) sx)) 2.0)
                (/ (- (+ ymin ymax) (* (1- rows) sy)) 2.0))
          ;; Even parity has the extra cell when both counts are odd.
          ;; Otherwise retain odd parity; the tied upper row ends at the right.
          (if (and (= (rem cols 2) 1) (= (rem rows 2) 1)) 0 1))))))
(defun wm:mesh (poly / xs ys xmin xmax ymin ymax sx sy nx ny row col row0 col0 centre verts ed a b key edges nodes found neighbors v p info kind half pair extra layout phase parity)
  (setq xs (mapcar 'car poly) ys (mapcar 'cadr poly) xmin (apply 'min xs) xmax (apply 'max xs) ymin (apply 'min ys) ymax (apply 'max ys)
    sx (/ (wm:cfg 'ml) 2.0) sy (/ (wm:cfg 'mw) 2.0)
    nx (+ 4 (fix (/ (- xmax xmin) sx))) ny (+ 4 (fix (/ (- ymax ymin) sy))) edges nil nodes nil wm:cells 0)
  (setq layout (wm:rect-layout poly sx sy) phase '(0.0 0.0) parity 1)
  (if layout
    (setq nx (car layout) ny (cadr layout) phase (caddr layout)
      parity (nth 3 layout) row0 0 col0 0)
    (setq row0 (1- (wm:floor (/ ymin sy))) col0 (1- (wm:floor (/ xmin sx)))))
  (if (> (* nx ny) (wm:cfg 'maxnodes)) (wm:fail "Surface trop grande : limite de securite 15000 noeuds. Diviser le panneau."))
  (setq row row0)
  (repeat ny
    (setq col col0)
    (repeat nx
      (if (= (abs (rem (+ row col) 2)) parity)
        (progn (setq centre (wm:add phase (list (* col sx) (* row sy)))
          verts (mapcar '(lambda (v) (wm:add centre v)) (list (list (- sx) 0.0) (list 0.0 sy) (list sx 0.0) (list 0.0 (- sy)))))
          ;; A cell is admitted only if all four vertices and all its edges fit.
          (if (and (vl-every '(lambda (v) (wm:inside v poly)) verts)
            (vl-every '(lambda (ed) (and (= (length (wm:clip (car ed) (cadr ed) poly)) 1)
              (equal (car (car (wm:clip (car ed) (cadr ed) poly))) (car ed) 1e-5)
              (equal (cadr (car (wm:clip (car ed) (cadr ed) poly))) (cadr ed) 1e-5))) (wm:edges verts)))
            (progn (setq wm:cells (1+ wm:cells)) (foreach ed (wm:edges verts)
              (setq a (car ed) b (cadr ed))
              (if (> (car a) (car b)) (setq v a a b b v))
              (setq key (strcat (wm:key a) "/" (wm:key b)))
              (if (not (assoc key edges))
                (progn (setq edges (cons (list key a b) edges))
                  (foreach pair (list (list a b) (list b a))
                    (setq p (car pair) key (wm:key p) found (assoc key nodes))
                    (if found (setq nodes (subst (list key p (cons (cadr pair) (caddr found))) found nodes))
                      (setq nodes (cons (list key p (list (cadr pair))) nodes)))))))))))
      (setq col (1+ col))) (setq row (1+ row)))
  (setq extra (wm:missing-edges nodes poly sx sy) edges (append extra edges)
    half (wm:half))
  (foreach ed edges
    (setq a (wm:add (cadr ed) (list half 0.0)) b (wm:sub (caddr ed) (list half 0.0)))
    (wm:draw (wm:bezier a
      (wm:add a (list (if (= (wm:cfg 'woven) 1) (min 8.0 (* 0.16 (wm:cfg 'ml))) 8.0) 0.0))
      (wm:sub b (list (if (= (wm:cfg 'woven) 1) (min 8.0 (* 0.16 (wm:cfg 'ml))) 8.0) 0.0)) b) (wm:cfg 'wire) nil))
  (foreach found nodes
    (setq p (cadr found) neighbors (caddr found) kind nil)
    (if (= (length neighbors) 2)
      (progn (setq info (wm:near p wm:inner) kind (if (> (abs (car (cadr info))) 0.7071) "LOOP" "EYE"))
        (setq wm:cuts (cons (list (car found) (car found) kind p) wm:cuts))))
    (if (/= kind "EYE")
      (progn
        (if (and (= (wm:cfg 'woven) 1) (= kind "LOOP"))
          (wm:draw (list (wm:sub p (list half 0.0)) (wm:add p (list half 0.0))) (wm:cfg 'wire) nil)
          (wm:insert wm:bead p 0.0))
        (setq wm:nodes (1+ wm:nodes)))))
  (princ))
(defun wm:back (pts / edges e ts s t0 mid run seg)
  (foreach e (mapcar 'list pts (cdr pts))
    (setq ts (wm:breaks (car e) (cadr e) (list wm:inner wm:outer)))
    (while (cdr ts)
      (setq s (car ts) t0 (cadr ts) mid (wm:lerp (car e) (cadr e) (/ (+ s t0) 2.0)))
      (if (or (wm:inside mid wm:inner) (not (wm:inside mid wm:outer)))
        (progn (setq seg (list (wm:lerp (car e) (cadr e) s) (wm:lerp (car e) (cadr e) t0)))
          (if (and run (< (distance (car run) (car seg)) 1e-5)) (setq run (cons (cadr seg) run))
            (progn (if run (wm:draw (reverse run) (wm:cfg 'lace) nil)) (setq run (list (cadr seg) (car seg))))))
        (progn (if run (wm:draw (reverse run) (wm:cfg 'lace) nil)) (setq run nil)))
      (setq ts (cdr ts))))
  (if run (wm:draw (reverse run) (wm:cfg 'lace) nil)))
(defun wm:at (chain poly / per e len a b out)
  (setq per 0.0) (foreach e (wm:edges poly) (setq per (+ per (distance (car e) (cadr e)))))
  (setq chain (rem (+ chain per) per))
  (foreach e (wm:edges poly)
    (if (not out) (progn (setq a (car e) b (cadr e) len (distance a b))
      (if (<= chain len) (setq out (list (wm:lerp a b (/ chain len)) (wm:unit (wm:sub b a))))
        (setq chain (- chain len)))))) out)
;; Find exactly one real convex corner between consecutive perimeter anchors.
;; Small turns from tessellated arcs, concave corners and like terminals retain
;; the classic lacing. Chain distances also handle the closing polygon edge.
(defun wm:corner (pair per / edges previous e chain delta hits t1 t2)
  (if (and (= (wm:cfg 'corner-auto) 1)
           (/= (caddar pair) (caddr (cadr pair))))
    (progn
      (setq edges (wm:edges wm:inner) previous (car (reverse edges)) chain 0.0 hits nil)
      (foreach e edges
        (setq delta (rem (+ (- chain (caar pair)) per) per)
          t1 (wm:unit (wm:sub (cadr previous) (car previous)))
          t2 (wm:unit (wm:sub (cadr e) (car e))))
        (if (and (> delta 1e-5) (< delta (- wm:pitch 1e-5))
                 (< (wm:dot t1 t2) 0.8660254))
          (setq hits (cons (list (car e) t1 t2 delta
            (> (wm:cross t1 t2) 1e-6)) hits)))
        (setq chain (+ chain (distance (car e) (cadr e))) previous e))
      (if (and (= (length hits) 1) (nth 4 (car hits))) (car hits)))))
;; Measure the frame locally, independent of tube width and polygon rotation.
(defun wm:frame-at (chain / info n ray ts e v outer)
  (setq info (wm:at chain wm:inner)
    n (list (cadr (cadr info)) (- (car (cadr info))))
    ray (wm:add (car info) (wm:mul n 10000.0)) ts nil)
  (foreach e (wm:edges wm:outer)
    (if (setq v (wm:hit (car info) ray (car e) (cadr e)))
      (if (> v 1e-7) (setq ts (cons v ts)))))
  (if ts
    (progn (setq outer (wm:lerp (car info) ray (apply 'min ts)))
      (list (wm:lerp (car info) outer 0.5) (cadr info)
        (distance (car info) outer) outer))))
;; Bridge the side / top (or bottom) behind the frame, without an extra turn
;; around its outside corner. Leg visibility agrees with adjacent windings.
;; Both visible fragments belong to one conceptual lacing path.
;; Perimeter winding invariant: one front leg and one rear leg per anchor.
;; Both LOOP and EYE have an incoming front leg and an outgoing rear leg.
(defun wm:leg-record (anchor visible / key found item)
  (setq key (wm:key anchor) found (assoc key wm:visibility)
    item (if found found (list key 0 0)))
  (setq item (list key (+ (cadr item) (if visible 1 0)) (+ (caddr item) (if visible 0 1))))
  (setq wm:visibility (if found (subst item found wm:visibility) (cons item wm:visibility))))
(defun wm:leg (pts anchor visible)
  (wm:leg-record anchor visible)
  (if visible (wm:draw pts (wm:cfg 'lace) nil) (wm:back pts)))
(defun wm:corner-legs (front rear pair / p np)
  (setq p (cadar pair) np (cadadr pair))
  (if (= (caddar pair) "EYE")
    (progn (wm:leg front p nil) (wm:leg rear np T))
    (progn (wm:leg front np T) (wm:leg rear p nil))))
;; Round a supplementary corner bridge on the actual outer tube face.
;; The rounding and all control handles follow its measured local width.
(defun wm:corner-return (pair bridge width / eye loop info t0 n dir radius rise ef er peak df db cf cb k h hp hn front rear cap eye-front)
  (setq eye (if (= (caddar pair) "EYE") (cadar pair) (cadadr pair))
    loop (if (= (caddar pair) "LOOP") (cadar pair) (cadadr pair))
    info (wm:near bridge wm:outer) t0 (cadr info)
    n (list (cadr t0) (- (car t0)))
    dir (if (> (wm:dot t0 (wm:sub loop eye)) 0.0) t0 (wm:mul t0 -1.0))
    radius (min (* width 0.16) (* (distance eye loop) 0.14)) rise (* radius 0.33)
    ef (wm:sub bridge (wm:mul dir radius)) er (wm:add bridge (wm:mul dir radius))
    peak (wm:add bridge (wm:mul n rise)) k 0.55228475
    df (wm:unit (wm:sub ef eye)) db (wm:unit (wm:sub loop er))
    cf (min (* k radius) (/ (* k rise) (max 0.25 (abs (wm:dot df n)))))
    cb (min (* k radius) (/ (* k rise) (max 0.25 (abs (wm:dot db n)))))
    h (min (* width 0.35) (* (distance eye loop) 0.22))
    hp (min (* width 0.16) (* (distance eye bridge) 0.12))
    hn (min (* width 0.35) (* (distance eye loop) 0.13) (* (distance loop bridge) 0.25))
    info (wm:near eye wm:inner) t0 (cadr info)
    front (wm:bezier eye (wm:add eye (wm:mul (list (cadr t0) (- (car t0))) hp))
      (wm:sub ef (wm:mul df h)) ef)
    rear (wm:bezier er (wm:add er (wm:mul db h)) (wm:sub loop (wm:mul dir hn)) loop)
    cap (append (wm:bezier ef (wm:add ef (wm:mul df cf)) (wm:sub peak (wm:mul dir (* k radius))) peak)
      (cdr (wm:bezier peak (wm:add peak (wm:mul dir (* k radius))) (wm:sub er (wm:mul db cb)) er)))
    eye-front (= (caddar pair) "LOOP"))
  (wm:leg-record eye eye-front) (wm:leg-record loop (not eye-front))
  (if eye-front
    (progn (wm:draw (append front (cdr cap)) (wm:cfg 'lace) nil) (wm:back rear))
    (progn (wm:back front) (wm:draw (append cap (cdr rear)) (wm:cfg 'lace) nil))))
(defun wm:corner-lace (pair corner / start delta f1 f2 q s t1 t2 det v r rail front rear p np rad a b qo so bridge)
  (setq start (caar pair) delta (cadddr corner)
    f1 (wm:frame-at (+ start (* delta 0.5)))
    f2 (wm:frame-at (+ start delta (* (- wm:pitch delta) 0.5))))
  (if (and f1 f2)
    (progn
      (setq q (car f1) s (car f2) t1 (cadr f1) t2 (cadr f2)
        det (wm:cross t1 t2))
      (if (> (abs det) 1e-8)
        (progn
          (setq v (/ (wm:cross (wm:sub s q) t2) det)
            r (wm:add q (wm:mul t1 v))
            rad (min (* 0.15 (min (caddr f1) (caddr f2)))
              (* 0.3 (distance q r)) (* 0.3 (distance r s)))
            a (wm:sub r (wm:mul t1 rad)) b (wm:add r (wm:mul t2 rad))
            rail (append (list q) (wm:bezier a
              (wm:add a (wm:mul t1 (* rad 0.55)))
              (wm:sub b (wm:mul t2 (* rad 0.55))) b) (list s)))
          ;; A narrow or irregular outer contour can invalidate this bridge.
          ;; In that case use the original return; never draw through the net.
          (if (vl-every '(lambda (a) (and (wm:inside a wm:outer)
                                         (not (wm:inside a wm:inner)))) rail)
            (progn
              (setq p (cadar pair) np (cadadr pair)
                qo (cadddr f1) so (cadddr f2))
              (if (or (and (= (caddar pair) "EYE") (nth 3 (car pair)))
                      (and (= (caddr (cadr pair)) "EYE") (nth 3 (cadr pair))))
                (progn
                  ;; The new eye already receives the lateral lacing from the
                  ;; preceding interval. This interval MUST go to the top/bottom
                  ;; face, not return a second time to the same lateral face.
                  (setq bridge (wm:frame-at (caddr (wm:near (wm:lerp p np 0.5) wm:inner))))
                  (if (and bridge (> (abs (car (cadr bridge))) 0.7071))
                    (setq bridge (cadddr bridge))
                    (setq bridge (if (= (caddar pair) "EYE") so qo)))
                  (wm:corner-return pair bridge (min (caddr f1) (caddr f2))))
                (progn
              (if (= (caddar pair) "EYE")
                (setq front (wm:bezier p (wm:lerp p qo 0.3) (wm:lerp p qo 0.7) qo)
                  rear (wm:bezier so
                    (wm:add so (wm:add (wm:mul t2 (* 0.6 (caddr f2)))
                      (wm:mul (list (cadr t2) (- (car t2))) (* -0.08 (caddr f2)))))
                    (wm:lerp so np 0.7) np))
                (setq front (wm:bezier so (wm:lerp so np 0.3) (wm:lerp so np 0.7) np)
                  rear (wm:bezier qo
                    (wm:add qo (wm:add (wm:mul t1 (* -0.6 (caddr f1)))
                      (wm:mul (list (cadr t1) (- (car t1))) (* -0.08 (caddr f1)))))
                    (wm:lerp qo p 0.7) p)))
              ;; Match the adjacent straight windings at BOTH anchors.
              ;; Match incoming-front / outgoing-rear at the two anchors.
              (wm:corner-legs front rear pair)
              (wm:back (append (list qo) rail (list so)))
                ))
              (setq wm:corners (1+ wm:corners)) T)))))))
(defun wm:lace (poly / anchors pair p nextp info normal tangent outerp ray ts v sign index pitch per phase edge1 edge2 radius rise arc peak side width turn-info normal-p normal-next h hp hn front-path back-path k e corner soft hug frontdir backdir cf cb)
  (setq anchors (vl-sort wm:anchors '(lambda (a b) (< (car a) (car b))))
    index 0 wm:corners 0 wm:visibility nil wm:boundary (length anchors) sign (if (> (wm:area wm:inner) 0) 1.0 -1.0) per 0.0 k 0.55228475)
  (foreach e (wm:edges wm:inner) (setq per (+ per (distance (car e) (cadr e)))))
  (foreach pair (mapcar 'list anchors (append (cdr anchors) (list (car anchors))))
    (setq p (cadar pair) nextp (cadadr pair) pitch (- (caadr pair) (caar pair)))
    (if (<= pitch 0) (setq pitch (+ pitch per)))
    (setq wm:pitch pitch corner (wm:corner pair per))
    (if (not (and corner (wm:corner-lace pair corner)))
      (progn
    (setq phase (+ (caar pair) (* 0.46 pitch)) info (wm:at phase wm:inner) tangent (cadr info)
      normal (wm:mul (list (cadr tangent) (- (car tangent))) sign)
      ray (wm:add (car info) (wm:mul normal 10000.0)) ts nil)
    (foreach e (wm:edges wm:outer) (if (setq v (wm:hit (car info) ray (car e) (cadr e))) (if (> v 1e-7) (setq ts (cons v ts)))))
    (if (not ts) (wm:fail "Le contour exterieur ne permet pas de retrouver le cadre a cette rive."))
    (setq outerp (wm:lerp (car info) ray (apply 'min ts)) width (distance (car info) outerp)
      turn-info (wm:near outerp wm:outer) tangent (cadr turn-info)
      normal (wm:mul (list (cadr tangent) (- (car tangent))) sign)
      side (> (abs (car normal)) (abs (cadr normal)))
      soft (and (not side) (= (caddar pair) "LOOP") (= (caddr (cadr pair)) "LOOP"))
      hug (and side (= (caddar pair) "EYE") (= (caddr (cadr pair)) "EYE")))
    ;; Actual local frame width drives both the return and the rounding.
    ;; The spacing between successive mesh vertices also limits the loop size.
    (setq radius (min (* width (cond (hug 0.10) (side 0.14) (soft 0.16) (T 0.28)))
        (* pitch (cond (hug 0.16) (soft 0.14) (T 0.18))))
      ;; At the side turn the INNER edge of the cable touches the profile.
      ;; Diameter supplies the centreline offset; frame width supplies the span.
      rise (if hug (/ (wm:cfg 'lace) 2.0) (* radius (cond (side 0.85) (soft 0.33) (T 0.50))))
      edge1 (wm:sub outerp (wm:mul tangent radius)) edge2 (wm:add outerp (wm:mul tangent radius))
      peak (wm:add outerp (wm:mul normal rise))
      info (wm:near p wm:inner) normal-p (if (nth 3 (car pair)) (nth 3 (car pair)) (wm:mul (list (cadr (cadr info)) (- (car (cadr info)))) sign))
      info (wm:near nextp wm:inner) normal-next (if (nth 3 (cadr pair)) (nth 3 (cadr pair)) (wm:mul (list (cadr (cadr info)) (- (car (cadr info)))) sign))
      h (min (* width 0.35) (* pitch 0.22))
      hp (min (* width 0.16) (* (distance p outerp) 0.12))
      hn (min (* width 0.16) (* (distance nextp outerp) 0.12)))
    ;; Two joined quarter-ellipses; tangents agree with both cable legs.
    ;; Free top/bottom lacing: a shallow return aligned with the oblique legs.
    ;; Local measured frame width and attachment pitch limit every handle.
    ;; Horizontal tangents at the mesh loops remove the pointed V-shaped cusp.
    (if (or soft hug)
      (progn
        (setq frontdir (wm:unit (wm:sub (if hug nextp p) (if hug edge2 edge1)))
          backdir (wm:unit (wm:sub (if hug p nextp) (if hug edge1 edge2)))
          cf (min (* k radius) (/ (* k rise) (max 0.25 (abs (wm:dot frontdir normal)))))
          cb (min (* k radius) (/ (* k rise) (max 0.25 (abs (wm:dot backdir normal)))))
          hp (min (* width 0.35) (* pitch 0.13) (* (distance p outerp) 0.25))
          hn (min (* width 0.35) (* pitch 0.13) (* (distance nextp outerp) 0.25)))
        (setq arc (wm:bezier edge1 (wm:sub edge1 (wm:mul (if hug backdir frontdir) (if hug cb cf)))
          (wm:sub peak (wm:mul tangent (* k radius))) peak))
        (setq arc (append arc (cdr (wm:bezier peak (wm:add peak (wm:mul tangent (* k radius)))
          (wm:sub edge2 (wm:mul (if hug frontdir backdir) (if hug cf cb))) edge2)))))
      (progn
        (setq arc (wm:bezier edge1 (wm:add edge1 (wm:mul normal (* k rise)))
          (wm:sub peak (wm:mul tangent (* k radius))) peak))
        (setq arc (append arc (cdr (wm:bezier peak (wm:add peak (wm:mul tangent (* k radius)))
          (wm:add edge2 (wm:mul normal (* k rise))) edge2))))))
    (if side
      (if hug
        (setq back-path (wm:bezier p (wm:add p (wm:mul normal-p hp))
            (wm:add edge1 (wm:mul backdir h)) edge1)
          front-path (wm:bezier edge2 (wm:add edge2 (wm:mul frontdir h))
            (wm:add nextp (wm:mul normal-next hn)) nextp))
        (setq back-path (wm:bezier p (wm:add p (wm:mul normal-p hp)) (wm:sub edge1 (wm:mul normal h)) edge1)
          front-path (wm:bezier edge2 (wm:sub edge2 (wm:mul normal h)) (wm:add nextp (wm:mul normal-next hn)) nextp)))
      (if soft
        (setq back-path (wm:bezier nextp (wm:sub nextp (wm:mul tangent hn))
            (wm:add edge2 (wm:mul backdir h)) edge2)
          front-path (wm:bezier edge1 (wm:add edge1 (wm:mul frontdir h))
            (wm:add p (wm:mul tangent hp)) p))
        (setq back-path (wm:bezier nextp (wm:add nextp (wm:mul normal-next hn)) (wm:sub edge2 (wm:mul normal h)) edge2)
          front-path (wm:bezier edge1 (wm:sub edge1 (wm:mul normal h)) (wm:add p (wm:mul normal-p hp)) p))))
    ;; Visibility comes from the anchor type, also on mixed fallback intervals.
    (wm:leg back-path (if side p nextp)
      (if side nil T))
    (wm:leg-record (if side nextp p)
      (if side T nil))
    (if (if side T nil)
      ;; Keep a single continuous polyline for the visible turn and leg.
      (wm:draw (append (if side arc (reverse arc)) (cdr front-path)) (wm:cfg 'lace) nil)
      (progn (wm:draw (if side arc (reverse arc)) (wm:cfg 'lace) nil) (wm:back front-path)))
    (if (and (= (caddar pair) "EYE") (= (rem index (wm:cfg 'stops)) 0))
      (wm:insert "JHR_WEBNET_BUTEE_4x4_V1" (wm:lerp p edge1 0.16) (angle p edge1)))
    ))
    (setq index (1+ index)))
  (if (or (/= (length wm:visibility) (length anchors))
    (not (vl-every '(lambda (rec) (and (= (cadr rec) 1) (= (caddr rec) 1))) wm:visibility)))
    (wm:fail "Alternance de lacage incoherente : chaque attache doit avoir un brin avant et un brin arriere.")))
(defun wm:block (name shapes / data)
  (if (tblsearch "BLOCK" name) (wm:fail "Nom de bloc deja utilise."))
  (setq wm:changed T)
  (entmake (list '(0 . "BLOCK") '(8 . "0") (cons 2 name) '(70 . 0) '(10 0.0 0.0 0.0)))
  (foreach data shapes (if (not (entmake data)) (wm:fail "Creation d un composant impossible.")))
  (entmake '((0 . "ENDBLK") (8 . "0"))))
(defun wm:bead-block (name w h / shapes x y r verts)
  (if (not (tblsearch "BLOCK" name))
    (progn (setq x (/ w 2.0) y (/ h 2.0) r 0.45
      verts (list (list (- x) (- r y)) (list (- r x) (- y)) (list (- x r) (- y)) (list x (- r y))
        (list x (- y r)) (list (- x r) y) (list (- r x) y) (list (- x) (- y r))))
      (setq shapes (list (wm:pline-data verts 0.12 T)
        (wm:pline-data (list (list (+ (- x) 0.7) (+ (- y) 0.5)) (list (+ (- x) 0.7) (- y 0.5))) 0.10 nil)
        (wm:pline-data (list (list (- x 0.7) (+ (- y) 0.5)) (list (- x 0.7) (- y 0.5))) 0.10 nil)))
      (wm:block name shapes))))
(defun wm:weave-block (name / half width shapes strand j u p run previous sign)
 (if (not (tblsearch "BLOCK" name))
  (progn
   (setq half (wm:half) width (wm:cfg 'wire) shapes nil)
   (foreach strand '(1.0 -1.0)
    (setq j 0 run nil)
    (repeat 65
     (setq u (/ j 64.0) p (list (+ (- half) (* 2 half u)) (* strand width 0.35 (sin (* 4 pi u)))))
     ;; Small breaks alternate at crossings to show which rope passes underneath.
     (if (and (> j 1) (< j 63) (< (abs (sin (* 4 pi u))) 0.28)
          (< (* strand (cos (* 4 pi u))) 0.0))
      (progn (if (> (length run) 1) (setq shapes (cons (wm:pline-data (reverse run) width nil) shapes))) (setq run nil))
      (setq run (cons p run)))
     (setq j (1+ j)))
    (if (> (length run) 1) (setq shapes (cons (wm:pline-data (reverse run) width nil) shapes))))
   (wm:block name (reverse shapes)))))
(defun wm:eye-block (/ name outline holes pts j ang)
  (setq name "JHR_WEBNET_OEIL_0150_B16_H8_3_V1")
  (if (not (tblsearch "BLOCK" name))
    (progn (setq pts '((0.0 -2.0) (8.0 -4.15)) j 0)
      (repeat 17 (setq ang (+ (- (/ pi 2.0)) (* pi (/ j 16.0)))
        pts (append pts (list (list (+ 11.85 (* 4.15 (cos ang))) (* 4.15 (sin ang))))) j (1+ j)))
      (setq pts (append pts '((8.0 4.15) (0.0 2.0))))
      (wm:block name (list (wm:pline-data pts 0.15 T) (wm:pline-data (wm:circle-points '(12.0 0.0) 1.5) 0.12 T)
        (wm:pline-data '((1.5 -1.6) (1.5 1.6)) 0.10 nil) (wm:pline-data '((3.0 -1.6) (3.0 1.6)) 0.10 nil))))))
(defun wm:offset (en gap / obj results valid sign raw o p candidates)
  (setq obj (vlax-ename->vla-object en) valid nil)
  (foreach sign '(-1 1)
    (if (not valid)
      (progn (setq raw (vl-catch-all-apply 'vlax-invoke (list obj 'Offset (* sign gap))))
        (if (not (vl-catch-all-error-p raw))
          (progn (if raw (setq wm:changed T)) (setq candidates nil) (foreach o raw
            (setq wm:temps (cons o wm:temps) p (wm:poly (vlax-vla-object->ename o)))
            (if (and (> (abs (wm:area p)) 1.0) (< (abs (wm:area p)) (abs (wm:area wm:inner)))
                 (vl-every '(lambda (q) (wm:inside q wm:inner)) p)) (setq candidates (cons p candidates))))
          (if (> (length candidates) 1) (wm:fail "Le retrait divise le filet en plusieurs panneaux. Traiter chaque panneau separement."))
          (if candidates (setq valid (car candidates))))))))
  (if (not valid) (wm:fail "Retrait du filet impossible. Reduire le retrait ou verifier la polyligne interieure.")) valid)
(defun wm:validate (en / data)
  (setq data (entget en))
  (if (or (/= (cdr (assoc 0 data)) "LWPOLYLINE") (= (logand 1 (cdr (assoc 70 data))) 0))
    (wm:fail "Selectionner une polyligne 2D fermee."))
  (if (and (assoc 210 data) (not (equal (cdr (assoc 210 data)) '(0.0 0.0 1.0) 1e-8)))
    (wm:fail "Les contours doivent etre dessines dans le plan XY (normale Z).")) en)
(defun wm:selfcross (p / ed i j bad a b)
  (setq ed (wm:edges p) i 0 bad nil)
  (foreach a ed (setq j 0)
    (foreach b ed
      (if (and (> j (+ i 1)) (not (and (= i 0) (= j (1- (length ed))))) (wm:hit (car a) (cadr a) (car b) (cadr b))) (setq bad T))
      (setq j (1+ j))) (setq i (1+ i))) bad)
(defun wm:generate (inside outside / obj lo hi poly name index data ins first last shapes result)
  (setq wm:reason nil)
  (wm:settings-valid) (wm:validate inside) (wm:validate outside)
  (if (equal inside outside) (wm:fail "Les deux contours doivent etre differents."))
  (if (> (abs (- (cond ((cdr (assoc 38 (entget inside)))) (T 0.0)) (cond ((cdr (assoc 38 (entget outside)))) (T 0.0)))) 0.01)
    (wm:fail "Les deux contours doivent etre coplanaires."))
  (setq obj (vlax-ename->vla-object inside)) (vla-GetBoundingBox obj 'lo 'hi)
  (setq lo (vlax-safearray->list lo) hi (vlax-safearray->list hi)
    wm:origin (mapcar '(lambda (a b) (/ (+ a b) 2.0)) (list (car lo) (cadr lo)) (list (car hi) (cadr hi)))
    wm:angle (wm:cfg 'angle) wm:inner (wm:poly inside) wm:outer (wm:poly outside))
  (if (< (wm:area wm:inner) 0) (setq wm:inner (reverse wm:inner)))
  (if (< (wm:area wm:outer) 0) (setq wm:outer (reverse wm:outer)))
  (if (or (wm:selfcross wm:inner) (wm:selfcross wm:outer)) (wm:fail "Contour croise ou auto-intersectant."))
  (if (or (not (vl-every '(lambda (p) (wm:inside p wm:outer)) wm:inner))
          (vl-some '(lambda (a) (vl-some '(lambda (b) (wm:hit (car a) (cadr a) (car b) (cadr b))) (wm:edges wm:outer))) (wm:edges wm:inner)))
    (wm:fail "Le contour exterieur doit entourer strictement le contour interieur sans le couper."))
  (setq poly (wm:offset inside (wm:cfg 'gap)) wm:netpoly poly wm:anchors nil wm:cuts nil wm:shapes nil wm:nodes 0 wm:boundary 0
    wm:bead (if (= (wm:cfg 'woven) 1)
      (strcat "JHR_MAILLE_TRESSE_D" (vl-string-translate "." "_" (rtos (wm:cfg 'wire) 2 3)) "_V1")
      (strcat "JHR_WEBNET_DOUILLE_" (vl-string-translate "." "_" (rtos (wm:cfg 'sleeve-l) 2 2)) "x"
        (vl-string-translate "." "_" (rtos (wm:cfg 'sleeve-h) 2 2)) "_V1")))
  (princ (if (= (wm:cfg 'woven) 1) "\nCreation de la maille tressee sans bagues..." "\nCreation de la maille et des douilles...")) (wm:mesh poly)
  (wm:terminals)
  (if (< (length wm:anchors) 4) (wm:fail "Cadre trop petit pour ces dimensions de maille."))
  (wm:lace poly)
  (wm:eye-block)
  (if (= (wm:cfg 'woven) 1) (wm:weave-block wm:bead) (wm:bead-block wm:bead (wm:cfg 'sleeve-l) (wm:cfg 'sleeve-h)))
  (wm:bead-block "JHR_WEBNET_BUTEE_4x4_V1" 4.0 4.0)
  (setq index 1) (while (tblsearch "BLOCK" (strcat "JHR_MAILLE_2D_" (itoa index))) (setq index (1+ index)))
  (setq name (strcat "JHR_MAILLE_2D_" (itoa index))) (wm:block name (reverse wm:shapes))
  (setq data (wm:insert-data name wm:origin wm:angle))
  (setq data (subst (cons 8 (getvar "CLAYER")) (assoc 8 data) data)
    data (subst (cons 10 (list (car wm:origin) (cadr wm:origin) (caddr lo))) (assoc 10 data) data))
  (entmake data) (setq ins (entlast))
  (regapp "JHR_WEBNET")
  (entmod (append (entget ins) (list (list -3 (list "JHR_WEBNET" (cons 1000 (strcat "representation2D;maille_centre_centre;accessoires_schematiques;mode=" (if (= (wm:cfg 'woven) 1) "tresse" "bagues")))
    (cons 1040 (wm:cfg 'wire)) (cons 1040 (wm:cfg 'lace)) (cons 1040 (wm:cfg 'mw)) (cons 1040 (wm:cfg 'ml))
    (cons 1005 (cdr (assoc 5 (entget inside)))) (cons 1005 (cdr (assoc 5 (entget outside)))))))))
  (if (wm:product-xdata)
   (entmod (subst (list -3 (append (cadr (assoc -3 (entget ins '("JHR_WEBNET")))) (wm:product-xdata)))
    (assoc -3 (entget ins '("JHR_WEBNET"))) (entget ins '("JHR_WEBNET")))))
  (setq *wm:last* ins)
  (princ (strcat "\n" name " : " (itoa wm:cells) " losanges complets, " (itoa wm:nodes) (if (= (wm:cfg 'woven) 1) " jonctions de maille sans bagues, " " douilles de maille, ") (itoa wm:boundary) " raccords de rive, " (itoa wm:corners) " transitions d angle, " (itoa wm:extensions) " brins avec oeillet ajoutes. Tout le contenu est sur le calque 0.")) ins)
(defun wm:cleanup () (foreach o wm:temps (vl-catch-all-apply 'vla-Delete (list o))) (setq wm:temps nil))
(defun c:JHRMAILLECLI (/ *error* doc inside outside result wm:temps wm:origin wm:angle wm:inner wm:outer wm:netpoly wm:shapes wm:anchors wm:nodes wm:boundary wm:bead wm:cuts wm:eyes wm:loops wm:corners wm:extensions wm:pitch wm:visibility begun wm:reason wm:changed)
  (defun *error* (msg)
    (wm:cleanup) (if begun (vla-EndUndoMark doc))
    (if wm:reason (princ (strcat "\nMaille non creee : " wm:reason)))
    (if (and (not wm:reason) msg (not (wcmatch (strcase msg) "*CANCEL*,*QUIT*,*BREAK*,*ANNUL*"))) (princ (strcat "\nMaille non creee : " msg))) (princ))
  (if (not (member (getvar "INSUNITS") '(0 4))) (wm:fail "Dessiner en millimetres avant de lancer JHRMAILLE."))
  (if (not (= (getvar "TILEMODE") 1)) (wm:fail "Lancer la commande dans l espace objet."))
  (setq inside (car (entsel "\n1 - Contour FERME interieur du cadre : ")))
  (if inside (progn (wm:validate inside) (setq outside (car (entsel "\n2 - Contour FERME exterieur du cadre : ")))
    (if outside (progn
      (setq doc (vla-get-ActiveDocument (vlax-get-acad-object))) (vla-StartUndoMark doc) (setq begun T)
      (setq result (vl-catch-all-apply 'wm:generate (list inside outside))) (wm:cleanup)
      (vla-EndUndoMark doc) (setq begun nil)
      (if (vl-catch-all-error-p result) (progn (if wm:changed (command "_.UNDO" "1")) (princ (strcat "\nMaille non creee : " (if wm:reason wm:reason (vl-catch-all-error-message result)))))
        (progn (vla-Regen doc 1) (princ "\nUn seul bloc ajoute ; les deux contours sources sont conserves. ANNULER revient en une etape."))))))) (princ))
(defun wm:ask (k label / val)
  (initget 6) (setq val (getreal (strcat "\n" label " <" (rtos (wm:cfg k) 2 2) "> : ")))
  (if val (wm:set k val)))
(defun c:JHRMAILLEPARAMCLI (/ a n mode)
  (foreach item '((mw "Petite diagonale centre / centre (mm)") (ml "Grande diagonale centre / centre (mm)")
      (wire "Diametre cable de maille (mm)") (lace "Diametre cable de lacage (mm)") (gap "Retrait filet / face interieure du cadre (mm)")
      (sleeve-l "Longueur dessinee de la douille (mm)") (sleeve-h "Largeur dessinee de la douille (mm)"))
    (wm:ask (car item) (cadr item)))
  (setq a (getangle (strcat "\nDirection de la grande diagonale <" (rtos (* 180.0 (/ (wm:cfg 'angle) pi)) 2 1) " deg> : ")))
  (if a (wm:set 'angle (+ a (angle '(0 0 0) (trans '(1 0 0) 1 0 T)))))
  (initget 6) (setq n (getint (strcat "\nPas des petites butees de rive <" (itoa (wm:cfg 'stops)) "> : ")))
  (if n (wm:set 'stops n))
  (initget "Auto Classique")
  (setq mode (getkword (strcat "\nRaccords d angle [Auto/Classique] <"
    (if (= (wm:cfg 'corner-auto) 1) "Auto" "Classique") "> : ")))
  (if mode (wm:set 'corner-auto (if (= mode "Auto") 1 0)))
  (princ "\nParametres memorises pour cette session. Lancer JHRMAILLE.") (princ))
(defun wm:ui (/ dll result keys vals product)
 (if (not (member "JHR:MAILLE-DIALOG-V120" (atoms-family 1)))
  (progn
   (setq dll (if *wm:ui-root* (strcat *wm:ui-root* "/JhrMailleUi_v1_2.dll") (findfile "JhrMailleUi_v1_2.dll")))
   (if (or (not dll) (not (findfile dll)))
    (wm:fail "Interface absente. NETLOAD JhrMailleUi_v1_2.dll du dossier complet, ou utiliser JHRMAILLECLI."))
   (command-s "_.NETLOAD" dll)))
 (if (not (member "JHR:MAILLE-DIALOG-V120" (atoms-family 1)))
  (wm:fail "Interface non chargee. Verifier le chargement .NET, ou utiliser JHRMAILLECLI."))
 (setq product (wm:product-current))
 (setq result (jhr:maille-dialog-v120 (wm:cfg 'ml) (wm:cfg 'mw) (wm:cfg 'wire) (wm:cfg 'lace) (wm:cfg 'gap)
   (* 180.0 (/ (wm:cfg 'angle) pi)) (wm:cfg 'woven) (wm:cfg 'corner-auto)
   (wm:cfg 'sleeve-l) (wm:cfg 'sleeve-h) (wm:cfg 'stops) (if product (car product) "")))
 ;; The managed ResultBuffer wraps a Nil value as (nil), not nil.
 (if (equal result '(nil)) (setq result nil))
 (if result
  (progn
   (if (or (/= (length result) 14)
       (not (vl-every 'numberp (reverse (wm:tail 3 (reverse result)))))
       (not (vl-every '(lambda (x) (= (type x) 'STR)) (wm:tail 11 result))))
    (wm:fail "Reponse invalide de l interface. Aucun parametre modifie."))
   (setq keys '(ml mw wire lace gap angle woven corner-auto sleeve-l sleeve-h stops) vals result)
   (while keys
    (wm:set (car keys) (cond ((= (car keys) 'angle) (* pi (/ (car vals) 180.0)))
      ((member (car keys) '(woven corner-auto stops)) (fix (car vals))) (T (car vals))))
    (setq keys (cdr keys) vals (cdr vals)))
   (setq *wm:product* (if (/= (nth 11 result) "") (wm:tail 11 result) nil)
     *wm:product-stamp* (if *wm:product* (wm:product-stamp) nil)) T)))
(defun c:JHRMAILLE (/ *error* wm:reason)
 (defun *error* (msg) (if wm:reason (princ (strcat "\n" wm:reason))) (princ))
 (if (not (member (getvar "INSUNITS") '(0 4))) (wm:fail "Dessiner en millimetres avant de lancer JHRMAILLE."))
 (if (/= (getvar "TILEMODE") 1) (wm:fail "Lancer la commande dans l espace objet."))
 (if (wm:ui) (c:JHRMAILLECLI) (princ "\nAnnule. Aucun objet ni parametre modifie.")) (princ))
(defun c:JHRMAILLEPARAM (/ *error* wm:reason)
 (defun *error* (msg) (if wm:reason (princ (strcat "\n" wm:reason))) (princ))
 (if (wm:ui) (princ "\nParametres memorises pour cette session. Lancer JHRMAILLE.")
   (princ "\nAnnule. Parametres conserves.")) (princ))
(princ "\nJHRMAILLE : interface et apercu, puis interieur / exterieur. JHRMAILLEPARAM : interface seule. JHRMAILLECLI : sans interface.")
(princ)
